[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"